# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: lydia.france@biology.ox.ac.uk
full_name: Lydia France
license: MIT
min_python_version: '3.10'
org: LydiaFrance
project_name: coderepro
project_short_description: 'An LLM tool for evaluating reproducibility of research
    code. '
python_name: coderepro
typing: no_typing
url: https://github.com/LydiaFrance/coderepro
